### ISSUE TITLE
Incorrect tagging of span:first-of-type

### ISSUE THREAD

**Issue by mcdonnelldean** [atom/language-less#30]
Hi!

When I have the following less:

```css
span:first-of-type {
  font-weight: bold;
}
```

Within another block of less it's incorrectly marked as `support type property-name css` but if I use any other html types or classes or even `span:last-of-type` it works as expected and applies `keyword control html elements` or some other slightly modified combination based on the value.

It just seems to be `span:first-of-type` that is the issue. I've had a look over the grammar but I don't see the issue, the rules all include first-of-type where applicable.

**Comment by braver** [comment]
One problem is that inside `{...}` the `span` is captured as a property name and then `:last-of-type` is also not recognised properly. We need the property-name regex to skip this case. 
The easiest solution is a positive look-ahead for a semi-colon at the end of a property declaration. I don't think Less requires them (for the last property in a list anyway), but it's sloppy without them. I implemented this in 987f146.

The second problem is that the custom-element regex is incorrectly matching `last-of-type`. (f5c8104)
All of this is complicated by the `property_value` range is too eager. I limited this by again requiring a property value to be terminated with a semi-colon. (c44b4f8).

All of this breaks the test, I'll look into that.

I'm adding these to my PR in #42. There is so much interaction between lines here that it's much easier to just continue that. Otherwise it's going to be a merge hell later on. Though, if it's better to split it up, let me know.

**Comment by braver** [comment]
Fixed the spec by switching to a negative lookahead so it doesn't require ';' after every property. I think this should fix it (note the `:hover` and the third `span`):

Before:
<img width="381" alt="before" src="https://cloud.githubusercontent.com/assets/2543659/10522967/3bb8bbdc-7378-11e5-98f9-e87d4a1feea1.png">

After:
<img width="342" alt="after" src="https://cloud.githubusercontent.com/assets/2543659/10522968/3be01b0a-7378-11e5-8d97-398a655c1c3a.png">
