### ISSUE TITLE
Autocomplete-plus - Problem on selector level

### ISSUE THREAD

**Issue by gustavpursche** [atom/language-less#34]
There is a difference in hitting Enter and hitting Space plus Enter as the next keystroke. I hope the picture can illustrate the problem a bit:

edit: comma works aswell, instead of space.

![autocomplete-plus-less](https://cloud.githubusercontent.com/assets/2244375/8038466/f8a7a904-0e03-11e5-8282-d1fa49df68ce.gif)

Not sure if the less-provider is the problem here, or whether the ticket should go to the autocomplete-plus package.

Version 0.207.0 (0.207.0)

**Comment by braver** [comment]
I think the grammar may be putting you in an incorrect scope there. Otherwise I really don't understand why you're getting property-name suggestions there. Could you perhaps have a look at the #42 PR to see if it's improved? Also, could you provide more information of the versions of Atom and packages you're using?

**Comment by 50Wliu** [comment]
I *think* this has been fixed a few times in [autocomplete-css](https://github.com/atom/autocomplete-css).  If it's still happening for you on Atom 1.2.0, please open a new issue on that repo.  Thanks!
