### ISSUE TITLE
text-overflow is not highlighted

### ISSUE THREAD

**Issue by devoncarew** [atom/language-less#39]
Previously filed at https://github.com/atom/language-css/issues/41, text-overflow is not highlighted.

**Comment by izuzak** [comment]
As I mentioned in atom/language-css#41, I think support for this was added in d0104de by @kevinsawicki, but it seems it was (accidentally?) removed in atom/language-less#16. 

@braver @kevinsawicki @simurai -- just to make sure I'm not missing anything, was `text-overflow` removed in atom/language-less#16 on purpose (in [this line](https://github.com/atom/language-less/pull/16/files#diff-14c55924b6cf1fe75bf40519b9cddaccL150))? Pinging you since you commented on that pull request.

**Comment by kevinsawicki** [comment]
>  just to make sure I'm not missing anything, was text-overflow removed in atom/language-less#16 on purpose (in this line)?

I don't think it was intentional and should definitely be added back if it is currently isn't highlighted correctly.

**Comment by braver** [comment]
Definitely not intentional. These files are almost impossible to diff for anything other than minor changes and this was such an overhaul that something like this just had to happen.
